################################################################################
###                                                                          ###
### Created by Alexandre Daby-Seesaram                                       ###
###                                                                          ###
### École Polytechnique, Palaiseau, France                                   ###
###                                                                          ###
################################################################################

project:
  resources:
    - "Figures"
    - "Template"
    - "Resources"
  type: website
  output-dir: public

title: "Quarto slide-template"
subtitle: "E4H flavour"
format: 
  revealjs:
    css: Template/ENSTA.css
    smaller: true
    html-math-method: mathjax
    author: 
        - name: Alexandre Daby-Seesaram <sup><span style="color:#a6ce39ff">[{{< iconify fa-brands:orcid >}}](https://orcid.org/0000-0002-2374-0971)</span></sup>
          email: alexandre.daby-seesaram@polytechnique.edu
          affiliations:
            - ref: lms
        - name: Second Author <sup><span style="color:#a6ce39ff">[{{< iconify fa-brands:orcid >}}](https://orcid.org/XXX)</span></sup>
          email: second.author@polytechnique.edu
          affiliations:
            - ref: lms
        - name: Third Author <sup><span style="color:#a6ce39ff">[{{< iconify fa-brands:orcid >}}](https://orcid.org/XXX)</span></sup>
          email: third.author@polytechnique.edu
          affiliations:
            - ref: lms
    affiliations:
    - id: lms
      name: LMS, École Polytechnique, Paris, France
    slide-number: c/t
    show-slide-number: all
    code-fold: true
    theme: Template/ENSTA_template.scss
    logo: Template/E4H_ENSTA.svg
    date: 09/10/2025
    date-format: long
    title-slide-attributes: 
        data-background-image: "Template/BG.svg"
jupyter: python3
execute:
  freeze: auto
progress: true
touch: true
controls: true
loadIcons: true
bibliography: Resources/template.bib
csl: Template/apa.csl
